name: Mbeezy_Clan_Death_System
version: '0.1'
main: de.wayvee.mbeezy.Main
api-version: '1.21'
description: Ein Plugin zum managing von Clantags und Toten
commands:
  setclan:
    description: Setzt dein Clantag.
  deaths:
    description: Zeigt dein aktuellen Todes counter.
  btown:
    description: DU bekommst ein 040 Btown Banger Item
    usage: /btown <1|2>
permissions:
  clandeathtracker.setclan:
    default: true
  clandeathtracker.btown:
    default: true
